services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: njs
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 80:4000
    environment:
      - PORT=4000
      - REDIS_URL=redis://storage
    entrypoint: ["node", "./dist/index.js"]
    depends_on:
      - storage
    links:
      - storage
volumes:
  logs_data: {}
