# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    volumes:
      - ./data:/data
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  counter:
    build:
      context: ./
      dockerfile: Dockerfile.local
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 80:4000
    environment:
      - PORT=4000
      - MONGODB_URL=mongodb://root:example@mongo:27017/admin
    entrypoint: [ "yarn", "dev" ]
    depends_on:
      - mongo
    links:
      - mongo
volumes:
  logs_data: { }
